### ISSUE TITLE
澎湃1.0.11.0.UMKCNXM 安卓14，杀后台严重，划卡后台一会就掉

### ISSUE THREAD

**Issue by 843944105** [dantmnf/NoSwipeToKill#3]
特别是支付宝，我想支付宝后台一直运行，结果还是杀后台

**Comment by dantmnf** [comment]
本模块仅适用于保留应用的前台服务（VPN、持续通知等）。

用户无感知，没有前台服务的应用，其后台保活不是本模块的适用场景。
